name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  csv: ^5.0.1  # Vérifie la dernière version sur pub.dev
  provider: ^6.0.0
  flutter_svg: ^2.0.0 # Ajout du package flutter_svg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/carte.svg
    - assets/All_enspd_location_room.csv